export let mock_data = [
  {
    id: 1,
    first_name: "Sebastiano",
    last_name: "McBryde",
    email: "smcbryde0@disqus.com",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Rebecca",
    last_name: "Umpleby",
    email: "rumpleby1@umich.edu",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Aguie",
    last_name: "Nancarrow",
    email: "anancarrow2@timesonline.co.uk",
    gender: "Male",
  },
  {
    id: 4,
    first_name: "Audrey",
    last_name: "Hubback",
    email: "ahubback3@cbslocal.com",
    gender: "Non-binary",
  },
  {
    id: 5,
    first_name: "Alameda",
    last_name: "Schaffler",
    email: "aschaffler4@google.ru",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Brinn",
    last_name: "Blaycock",
    email: "bblaycock5@weebly.com",
    gender: "Female",
  },
  {
    id: 7,
    first_name: "Jobie",
    last_name: "Velez",
    email: "jvelez6@dmoz.org",
    gender: "Bigender",
  },
  {
    id: 8,
    first_name: "Karola",
    last_name: "Phil",
    email: "kphil7@opera.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Ertha",
    last_name: "Antcliffe",
    email: "eantcliffe8@godaddy.com",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Paulina",
    last_name: "Morch",
    email: "pmorch9@epa.gov",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Alexei",
    last_name: "Fant",
    email: "afanta@macromedia.com",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Ewell",
    last_name: "Astridge",
    email: "eastridgeb@mail.ru",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Connor",
    last_name: "Joncic",
    email: "cjoncicc@state.gov",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Minni",
    last_name: "Horwell",
    email: "mhorwelld@blogs.com",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Anatol",
    last_name: "Hinners",
    email: "ahinnerse@opensource.org",
    gender: "Male",
  },
  {
    id: 16,
    first_name: "Dwight",
    last_name: "Kondrat",
    email: "dkondratf@shareasale.com",
    gender: "Non-binary",
  },
  {
    id: 17,
    first_name: "Verina",
    last_name: "Godspeede",
    email: "vgodspeedeg@nymag.com",
    gender: "Female",
  },
  {
    id: 18,
    first_name: "Dud",
    last_name: "Blade",
    email: "dbladeh@wsj.com",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Claudius",
    last_name: "Wehnerr",
    email: "cwehnerri@vk.com",
    gender: "Male",
  },
  {
    id: 20,
    first_name: "Silva",
    last_name: "Sharphurst",
    email: "ssharphurstj@reddit.com",
    gender: "Female",
  },
  {
    id: 21,
    first_name: "Jacob",
    last_name: "Meikle",
    email: "jmeiklek@wordpress.org",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Isacco",
    last_name: "Iaduccelli",
    email: "iiaduccellil@nps.gov",
    gender: "Male",
  },
  {
    id: 23,
    first_name: "Geordie",
    last_name: "Sharvill",
    email: "gsharvillm@diigo.com",
    gender: "Polygender",
  },
  {
    id: 24,
    first_name: "Jasmin",
    last_name: "Woolfenden",
    email: "jwoolfendenn@businessinsider.com",
    gender: "Female",
  },
  {
    id: 25,
    first_name: "Berta",
    last_name: "Dumbrill",
    email: "bdumbrillo@marriott.com",
    gender: "Female",
  },
  {
    id: 26,
    first_name: "Casey",
    last_name: "Verity",
    email: "cverityp@soup.io",
    gender: "Genderqueer",
  },
  {
    id: 27,
    first_name: "Davidde",
    last_name: "O'Moylane",
    email: "domoylaneq@adobe.com",
    gender: "Genderfluid",
  },
  {
    id: 28,
    first_name: "Diane-marie",
    last_name: "Pyke",
    email: "dpyker@shinystat.com",
    gender: "Female",
  },
  {
    id: 29,
    first_name: "Tate",
    last_name: "Cartmel",
    email: "tcartmels@stanford.edu",
    gender: "Male",
  },
  {
    id: 30,
    first_name: "Wren",
    last_name: "O'Hengerty",
    email: "wohengertyt@imageshack.us",
    gender: "Agender",
  },
  {
    id: 31,
    first_name: "Sherm",
    last_name: "Liger",
    email: "sligeru@utexas.edu",
    gender: "Male",
  },
  {
    id: 32,
    first_name: "Ransell",
    last_name: "Kaminski",
    email: "rkaminskiv@nbcnews.com",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Annecorinne",
    last_name: "Buttel",
    email: "abuttelw@edublogs.org",
    gender: "Female",
  },
  {
    id: 34,
    first_name: "Vita",
    last_name: "Cosham",
    email: "vcoshamx@webs.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Tremaine",
    last_name: "Barnhill",
    email: "tbarnhilly@soundcloud.com",
    gender: "Agender",
  },
  {
    id: 36,
    first_name: "Gardener",
    last_name: "Freer",
    email: "gfreerz@rediff.com",
    gender: "Male",
  },
  {
    id: 37,
    first_name: "Alicea",
    last_name: "de Verson",
    email: "adeverson10@ebay.com",
    gender: "Female",
  },
  {
    id: 38,
    first_name: "Doralyn",
    last_name: "Grayston",
    email: "dgrayston11@wunderground.com",
    gender: "Female",
  },
  {
    id: 39,
    first_name: "Kelby",
    last_name: "Yarnold",
    email: "kyarnold12@google.com.br",
    gender: "Male",
  },
  {
    id: 40,
    first_name: "Daffy",
    last_name: "Acklands",
    email: "dacklands13@xing.com",
    gender: "Polygender",
  }
];

export function getData(page: number) {
  let per_page = 10;
  if (page == 1) {
    return mock_data.slice(0, per_page);
  } else {
    return mock_data.slice(per_page * page - 10, per_page * page);
  }
}
